### ISSUE TITLE
Godot release 4.3 update.

### ISSUE THREAD

**Issue by viksl** [RoboPoets/digital_human#4]
Hi,
I just want to ask if you are ok with it, will you be bumping this up for 4.3 (the release seems to be unless more issues surface sometimes in the next week probably).

Secondly, since the last update was 8 months ago, did you drop this project, please?
(No pressure, it's a really nice thing so I'm just curious about the future of your project? :)).

Thank you very much!

**Comment by and-rad** [comment]
The project is not dropped, but development will be slow for a while because I'm currently busy with preparing the release of [Days of Defiance](https://defiance.robopoets.com/en/), which is going to take all the time I have available.

I have big plans for this project and will return to it as soon as I'm not as busy anymore.

**Comment by viksl** [comment]
Oh that's a pretty cool project you have there :).
So not even bumping it up for the 4.3 I take it? Thanks and good luck with your game!

**Comment by and-rad** [comment]
Bumping is going to happen, but only after 4.3 is actually released.
